name: "indic_xlit"
backend: "python"
max_batch_size: 32

input [
  {
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [ -1 ]
  },
  {
    name: "TARGET_LANG"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "SOURCE_LANG"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "TRANSLITERATION"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

dynamic_batching {
  max_queue_delay_microseconds: 100
}
